server:
  port: 8080

service:
  message: API Gateway loaded from Github config repo

spring:
  data:
    redis:
      host: localhost
      port: 6379
      
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service-route
              uri: lb://product-service
              predicates:
                - Path=/api/products,/api/products/**
              filters:
                - StripPrefix=0
                - AddResponseHeader=X-Platform, microservices-pro
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    redis-rate-limiter.requestedTokens: 1
                    key-resolver: "#{@ipKeyResolver}"

            - id: inventory-service-route
              uri: lb://inventory-service
              predicates:
                - Path=/api/inventory,/api/inventory/**
              filters:
                - StripPrefix=0
                - AddResponseHeader=X-Platform, microservices-pro

jwt:
  secret: ${JWT_SECRET:361a65ca5fde3dcf658a71a7b93bd8cf3b17d564a5e5cae93aac497a890978b5}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
